// Code generated by "stringer -type=Type"; DO NOT EDIT.

package go_socketio_parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Connect-0]
	_ = x[Disconnect-1]
	_ = x[Event-2]
	_ = x[Ack-3]
	_ = x[Error-4]
	_ = x[BinaryEvent-5]
	_ = x[BinaryAck-6]
}

const _Type_name = "ConnectDisconnectEventAckErrorBinaryEventBinaryAck"

var _Type_index = [...]uint8{0, 7, 17, 22, 25, 30, 41, 50}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
